name: Scrape UCSD schedules (TSS)
run-name: Scrape UCSD schedules (${{ format('{0}{1}', inputs.quarter, inputs.year) }}) from TSS

on:
  workflow_dispatch:
    inputs:
      year:
        description: Last two digits of the year
        required: true
        type: string
      quarter:
        description: Quarter
        required: true
        type: choice
        options:
          - FA
          - WI
          - SP
          - SA

permissions:
  contents: write

jobs:
  scrape:
    name: Scrape TSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v7
        with:
          node-version: '26'
      - name: Scrape sections
        env:
          TERM: ${{ inputs.quarter }}${{ inputs.year }}
        run: |
          echo "Scraping $TERM"
          node tss/index.ts $TERM
          node tss/coursesToFile.ts $TERM
          node tss/enrollment-data.ts
      - name: Move files
        run: |
          mkdir .data
          mv classrooms-*.txt .data
          mv tss/enrollment-data.tsv .data
      - name: Upload scraped data
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: ./.data/
  upload:
    name: Upload scraped data to gh-pages
    runs-on: ubuntu-latest
    needs: scrape
    concurrency:
      group: gh-pages-upload
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v4
        with:
          name: data
          path: ~/data/
      - name: Push scraped data to gh-pages
        env:
          TERM: ${{ inputs.quarter }}${{ inputs.year }}
        run: |
          cp -v ~/data/* ./data/
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./data/
          git commit -m "Scrape $TERM (TSS)"
          git push
